# markdown adn highlighter
markdown:    kramdown
highlighter: rouge

# permalinks
permalink:  pretty

# Server
#url:        noobscroll.js.org
#baseurl:    ./

# Custom variables
version:    v1.0.3
noobscroll:
  repo:       https://github.com/arguiot/NoobScroll
  download:   https://github.com/arguiot/NoobScroll/releases/download/v1.0.2/noobscroll.min.js
  docs:       https://github.com/arguiot/NoobScroll/wiki
  stargazers: https://github.com/arguiot/NoobScroll/stargazers
  cdn:        https://unpkg.com/noobscroll
displayjs:
  repo:       https://github.com/arguiot/DisplayJS
  download:   https://unpkg.com/display.js
  docs:       https://github.com/arguiot/DisplayJS/wiki
  stargazers: https://github.com/arguiot/DisplayJS/stargazers
  cdn:        https://unpkg.com/display.js

author:
  github:   https://github.com/arguiot
  twitter:  https://twitter.com/arthur_guiot
  mail: mailto:arguiot@gmail.com
  facebook: https://www.facebook.com/profile.php?id=100012180104056
inspiration:
  github:   https://github.com/lucasgruwez

tweet:      https://twitter.com/intent/tweet?screen_name=arthur_guiot
about:      about
