# markdown adn highlighter
markdown:    kramdown
highlighter: rouge

# permalinks
permalink:  pretty

# Server
#url:        noobscroll.js.org
#baseurl:    ./

# Custom variables
version:    v1.0.3
cdn:        https://unpkg.com/noobscroll
noobscroll:
  repo:       https://github.com/arguiot/NoobScroll
  download:   https://github.com/arguiot/NoobScroll/releases/download/v1.0.2/noobscroll.min.js
  docs:       https://github.com/arguiot/NoobScroll/wiki
  stargazers: https://github.com/arguiot/NoobScroll/stargazers

npm:        https://www.npmjs.com/package/noobscroll
author:
  github:   https://github.com/arguiot
  twitter:  https://twitter.com/arthur_guiot
  mail: mailto:arguiot@gmail.com
inspiration:
  github:   https://github.com/lucasgruwez

tweet:      https://twitter.com/intent/tweet?screen_name=arthur_guiot
