---
hide_body: false
is_partial: false
fields:
- type: text
  name: layout
  hidden: true
  default: post
  config:
    required: true
- type: text
  name: title
  label: Title
  description: The post title
  config:
    required: true
  default: New Post
- type: datetime
  name: date
  label: date
  description: The time your post was published
  config:
    required: true
- type: file
  name: image
  label: image
  description: The main image
pages:
- _posts/2018-06-07-my-favorite-messaging-apps-of-2018.md
- _posts/2018-06-04-catch-errors-after-deployment.md
- _posts/2018-06-04-publishing-my-first-app-on-the-app-store.md
- _posts/2018-05-26-designing-the-video-of-theoremjs.md
- _posts/2018-05-20-almost-finished-theoremjs.md
- _posts/2018-05-20-mvc-will-really-help-you-debug-your-code-faster.md
- _posts/2018-05-19-releasing-protype.md
